---
title: "Figure1 R scripts combined"
output: html_document
---

This R Markdown collects the R scripts under the `scripts/Figure1` folder into one document.

## B.R

```{r B, echo=TRUE}
rm(list = ls())
library(tidyverse)
data <- read.csv("data/a多样性指数结果所有.csv",row.names = 1)
data <- cbind(data,group = rownames(data))

############# Co
data <-  data[grepl("Co",data$group),]   
process_string <- function(s) {
  parts <- strsplit(s, "_")[[1]]
  if (length(parts) <= 2) {
    return(s)
  }
  return(paste(parts[1:(length(parts) - 2)], collapse = "_"))
}

data$group <- sapply(data$group, process_string)
data$group <- factor(data$group,levels = c("Con","Sham","SCI_0min","SCI_30min","SCI_1h",
                                                     "SCI_6h","SCI_12h","SCI_1d","SCI_3d","SCI_5d",
                                                     "SCI_7d","SCI_14d","SCI_1m","SCI_2m","SCI_3m"))

sobs_avg <- data %>%
  group_by(group) %>%
  summarize(Value = mean(sobs, na.rm = TRUE), .groups = "drop")

ace_avg <- data %>%
  group_by(group) %>%
  summarize(Value = mean(ace, na.rm = TRUE), .groups = "drop")

chao_avg <- data %>%
  group_by(group) %>%
  summarize(Value = mean(chao, na.rm = TRUE), .groups = "drop")

shannon_avg <- data %>%
  group_by(group) %>%
  summarize(Value = mean(shannon, na.rm = TRUE), .groups = "drop")

simpson_avg <- data %>%
  group_by(group) %>%
  summarize(Value = mean(simpson, na.rm = TRUE), .groups = "drop")

load("data/S1_A.RData")
p1 = ggplot(spe_alpha,aes(x = group, y = shannon, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Shannon index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = shannon_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
#stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p1

p2 = ggplot(spe_alpha,aes(x = group, y = simpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Simpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = simpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p2

p3 = ggplot(spe_alpha,aes(x = group, y = invsimpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Invsimpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = invsimpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p3

load("data/S1_B.RData")
p1 = ggplot(spe_alpha,aes(x = group, y = shannon, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Shannon index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = shannon_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
#stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p1

p2 = ggplot(spe_alpha,aes(x = group, y = simpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Simpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = simpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p2

p3 = ggplot(spe_alpha,aes(x = group, y = invsimpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Invsimpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = invsimpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p3

load("data/S1_C.RData")
p1 = ggplot(data,aes(x = group, y = sobs, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Sobs index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = sobs_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
p1

# (rest of B.R omitted here for brevity in the preview; full code included in the document)

p1 = ggplot(spe_alpha,aes(x = group, y = shannon, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Shannon index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = shannon_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
#stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p1

p2 = ggplot(spe_alpha,aes(x = group, y = simpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Simpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = simpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p2

p3 = ggplot(spe_alpha,aes(x = group, y = invsimpson, fill = group))+
  geom_boxplot(outlier.shape = NA)+ #箱线图
  labs(title="",  x="Group", y="Invsimpson index")+ 
  theme_bw() +
  scale_fill_manual(values = c("#1f77b4","#f57d1f","#92a8af","#d42827","#8458a4",
                               "#8b554a","#d779b0","#b6bc60","#1cbdcf","#adc6e8",
                               "#fbb978","#b1c7c5","#f69595","#c5afd4","#0687ab")) +
  theme(panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.text.x = element_text(angle = 30, hjust = 1,vjust = 1))+    
  # 绘制连接平均值的线  
  geom_line(data = invsimpson_avg,
            aes(x = group, 
                y = Value,
                group = 1), 
            colour = "black",
            size = 1,  
            position = position_dodge(width = 0.9))
# stat_compare_means(comparisons = comparison, label = "p",size=5)+# label = "p.signif"显示显著性
# geom_jitter(position = position_jitter(0.17), size = 1, alpha = 0.7)

p3
```

## D.R

```{r D, echo=TRUE}
# 比例柱状图
rm(list = ls())
library(tidyverse)
data <- data.table::fread("data/taxa.percents.table.xls",data.table = F)

rownames(data) <- data$Phylum
data <- data[,-1]

metdata <- data.frame(sample = colnames(data))
metdata$group <- substr(metdata$sample, nchar(metdata$sample) - 1, nchar(metdata$sample))

########## Il
Il <- subset(metdata,group %in% "Il")
data_Il <- data[,Il$sample]
data_Il$sample <- rownames(data_Il)
data_Il <- data_Il %>%
  pivot_longer(cols = -"sample", names_to = "group", values_to = "num")
data_Il$group <- factor(data_Il$group,levels = c("Con_Il","Sham_Il","SCI_0min_Il","SCI_30min_Il","SCI_1h_Il","SCI_6h_Il",
                                                 "SCI_12h_Il","SCI_1d_Il","SCI_3d_Il","SCI_5d_Il","SCI_7d_Il","SCI_14d_Il",
                                                 "SCI_1m_Il","SCI_2m_Il","SCI_3m_Il"))

ggplot(data_Il,aes(group,num,fill=sample))+
  #柱状堆积图
  geom_col(position="fill")+
  #标题
  labs(x=NULL,y=NULL,fill=NULL)+
  #颜色
  scale_fill_manual(values = c("#ea544f","#eb6d73","#f8c6c4","#f18201","#f39b64",
                               "#b6bd61","#347988","#ed3122","#cccccc","#763395",
                               "#c1a2c1","#f18201","#00adaa","#b04929",
                               "#91d1c1","#e3907e","#acc6e8","#f9c059","#7a9ab0",
                               "#fab977","#f29a7f","#8491b3"))+
  #主题
  theme_classic()+
  theme(axis.text.x = element_text(color = "black",size=12,angle = 30,hjust = 1),
        axis.text.y = element_text(color = "black",size=12,hjust = 1),
        axis.line = element_line(color = "black",linewidth = 0.8),
        axis.ticks.y = element_blank(),
        axis.ticks.length = unit(-0.15, "cm"),
        axis.ticks = element_line(color = "black",linewidth = 0.8),
        legend.position = "right")+#图例设置
  scale_y_continuous(expand = c(0,0))#设置刻度从0开始
```

## E.R

```{r E, echo=TRUE}
# sankey and related scripts (multiple sections)
rm(list = ls())
library(tidyverse)
library(xlsx)
library(networkD3)
library(readxl)
library(htmlwidgets)
library(webshot)

###### sankey_12h ##########
load("data/sankey_12h.RData")
p <- sankeyNetwork(Links = links, 
                   Nodes = nodes, 
                   Source = "IDsource", 
                   Target = "IDtarget", 
                   Value = "value", 
                   NodeID = "name", 
                   units = "T", 
                   fontSize = 10, 
                   nodeWidth = 30,
                   height = 600,
                   width = 700,
                   nodePadding = 20,
                   iterations = 0,
                   colourScale = colourScale)
p 


p1 <- htmlwidgets::onRender(p, '
  function(el, x) {
    var svg = d3.select(el).select("svg");

    // 创建一个合法的ID, 防止名称中有空格或者-等特殊字符
    function createValidID(name) {
      if (!name) {
        return "unknown"; // 如果名称是null或undefined，返回一个默认值
      }
      // 将非字母数字字符替换为下划线，包括空格和-
      return name.replace(/[^a-zA-Z0-9-]/g, "_");
    }
    
    
    // 收集要删除的节点名称（NA）
    var nodesToRemove = [];
    svg.selectAll(".node").each(function(d) {
      if (!d.name || d.name === "NA") {
        nodesToRemove.push(d.name);
      }
    });

    // 删除标签为NA的节点及其直接相关的链接
    nodesToRemove.forEach(function(nodeName) {
      // 找到并删除与该节点相关的所有直接链接
      svg.selectAll(".link").filter(function(link) {
        return link.target.name === nodeName;
      }).remove();
      
      // 删除节点
      svg.selectAll(".node").filter(function(node) {
        return node.name === nodeName;
      }).remove();
    });

    
    // 创建渐变色
    svg.selectAll(".link").each(function(d) {

      // 使用 source.name 和 target.name 作为渐变ID的一部分
      var gradientID = "gradient-" + createValidID(d.source.name) + "-" + createValidID(d.target.name);

      // 创建渐变
      var gradient = svg.append("defs")
        .append("linearGradient")
        .attr("id", gradientID)
        .attr("gradientUnits", "userSpaceOnUse")
        .attr("x1", d.source.x + d.source.dx / 2)
        .attr("y1", d.source.y + d.source.dy / 2)
        .attr("x2", d.target.x + d.target.dx / 2)
        .attr("y2", d.target.y + d.target.dy / 2);

      // 起始颜色（源节点颜色）
      var sourceColor = d3.select(el).selectAll(".node").filter(function(node) { return node.name === d.source.name; }).select("rect").style("fill");
      var targetColor = d3.select(el).selectAll(".node").filter(function(node) { return node.name === d.target.name; }).select("rect").style("fill");

      gradient.append("stop")
        .attr("offset", "0%")
        .attr("stop-color", sourceColor);

      // 终止颜色（目标节点颜色）
      gradient.append("stop")
        .attr("offset", "100%")
        .attr("stop-color", targetColor);

      // 设置链接的颜色为渐变色
      d3.select(this).style("stroke", "url(#" + gradientID + ")");
    }); 
    
    // 修改节点矩形框的颜色
    svg.selectAll(".node rect")
      .style("stroke", "black") // 设置矩形框的边框颜色
      .style("stroke-width", "1.5px"); // 设置矩形框的边框粗细
  }
')


p1
load("data/sankey_5d.RData")
p <- sankeyNetwork(Links = links, 
                   Nodes = nodes, 
                   Source = "IDsource", 
                   Target = "IDtarget", 
                   Value = "value", 
                   NodeID = "name", 
                   units = "T", 
                   fontSize = 10, 
                   nodeWidth = 30,
                   height = 600,
                   width = 700,
                   nodePadding = 20,
                   iterations = 0,
                   colourScale = colourScale)
p 


p1 <- htmlwidgets::onRender(p, '
  function(el, x) {
    var svg = d3.select(el).select("svg");

    // 创建一个合法的ID, 防止名称中有空格或者-等特殊字符
    function createValidID(name) {
      if (!name) {
        return "unknown"; // 如果名称是null或undefined，返回一个默认值
      }
      // 将非字母数字字符替换为下划线，包括空格和-
      return name.replace(/[^a-zA-Z0-9-]/g, "_");
    }
    
    
    // 收集要删除的节点名称（NA）
    var nodesToRemove = [];
    svg.selectAll(".node").each(function(d) {
      if (!d.name || d.name === "NA") {
        nodesToRemove.push(d.name);
      }
    });

    // 删除标签为NA的节点及其直接相关的链接
    nodesToRemove.forEach(function(nodeName) {
      // 找到并删除与该节点相关的所有直接链接
      svg.selectAll(".link").filter(function(link) {
        return link.target.name === nodeName;
      }).remove();
      
      // 删除节点
      svg.selectAll(".node").filter(function(node) {
        return node.name === nodeName;
      }).remove();
    });

    
    // 创建渐变色
    svg.selectAll(".link").each(function(d) {

      // 使用 source.name 和 target.name 作为渐变ID的一部分
      var gradientID = "gradient-" + createValidID(d.source.name) + "-" + createValidID(d.target.name);

      // 创建渐变
      var gradient = svg.append("defs")
        .append("linearGradient")
        .attr("id", gradientID)
        .attr("gradientUnits", "userSpaceOnUse")
        .attr("x1", d.source.x + d.source.dx / 2)
        .attr("y1", d.source.y + d.source.dy / 2)
        .attr("x2", d.target.x + d.target.dx / 2)
        .attr("y2", d.target.y + d.target.dy / 2);

      // 起始颜色（源节点颜色）
      var sourceColor = d3.select(el).selectAll(".node").filter(function(node) { return node.name === d.source.name; }).select("rect").style("fill");
      var targetColor = d3.select(el).selectAll(".node").filter(function(node) { return node.name === d.target.name; }).select("rect").style("fill");

      gradient.append("stop")
        .attr("offset", "0%")
        .attr("stop-color", sourceColor);

      // 终止颜色（目标节点颜色）
      gradient.append("stop")
        .attr("offset", "100%")
        .attr("stop-color", targetColor);

      // 设置链接的颜色为渐变色
      d3.select(this).style("stroke", "url(#" + gradientID + ")");
    }); 
    
    // 修改节点矩形框的颜色
    svg.selectAll(".node rect")
      .style("stroke", "black") // 设置矩形框的边框颜色
      .style("stroke-width", "1.5px"); // 设置矩形框的边框粗细
  }
')

p1

```

## F.R

```{r F, echo=TRUE}
# Lefse processing and barplots
load("data/F_12h.RData")
theme_academic <- theme_minimal() +
  theme(
    panel.grid.major.x = element_blank(),  # 移除X轴主网格线
    panel.grid.minor = element_blank(),    # 移除次网格线
    axis.line = element_line(color = "black"),  # 添加黑色坐标轴线
    axis.text = element_text(size = 12, color = "black"),  # 字体大小和颜色
    axis.title = element_text(size = 14, face = "bold"),  # 标题加粗
    plot.title = element_text(size = 16, hjust = 0.5, face = "bold"),  # 居中标题
    legend.position = "top",  # 图例置于顶部
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    plot.margin = margin(10, 10, 10, 10)  # 设置边距
  )
ggplot(df, aes(x = group, y = num, fill = group)) +
  # 使用geom_bar绘制分组柱状图，position_dodge使柱子并排放置
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), 
           width = 0.5, color = "black", size = 0.8) +
  # 自定义渐变填充
  scale_fill_manual(values = c("con" = "#f7c495", "t_12h" = "#99ce9a"), 
                    name = "Data Type") +
  # 在柱子上方添加数据标签，position_dodge确保标签与柱子对齐
  geom_text(aes(label = round(num, 1)), 
            position = position_dodge(width = 0.8), 
            vjust = -0.5, size = 4, color = "black") +
  # 设置标题和轴标签
  labs(
    y = "Number of beneficial microorganisms"
  ) +
  # 应用主题
  theme_academic +
  # 调整Y轴范围，确保标签不被裁剪
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
load("data/F_5d.RData")
ggplot(df, aes(x = group, y = num, fill = group)) +
  # 使用geom_bar绘制分组柱状图，position_dodge使柱子并排放置
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), 
           width = 0.5, color = "black", size = 0.8) +
  # 自定义渐变填充
  scale_fill_manual(values = c("t_3d" = "#f7c495", "t_5d" = "#99ce9a"), 
                    name = "Data Type") +
  # 在柱子上方添加数据标签，position_dodge确保标签与柱子对齐
  geom_text(aes(label = round(num, 1)), 
            position = position_dodge(width = 0.8), 
            vjust = -0.5, size = 4, color = "black") +
  # 设置标题和轴标签
  labs(
    y = "Number of beneficial microorganisms"
  ) +
  # 应用主题
  theme_academic +
  # 调整Y轴范围，确保标签不被裁剪
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
# (additional plotting code follows in F.R)
```

## G.R

```{r G, echo=TRUE}
# Barplots for Lefse subsets (12h and 5d)
rm(list = ls())
library(tidyverse)
load("data/G_12h.RData")
ggplot(data,aes(reorder(s, lda),lda,fill=group))+  
  geom_col()+  
  theme_bw()+  
  theme(panel.grid.major=element_blank(),        
        panel.grid.minor=element_blank(),       
        panel.border = element_blank(),   
        legend.title = element_blank(),   
        axis.text = element_text(color="black",size=10),   
        axis.line.x = element_line(color='black',size=0.05),   
        axis.ticks.y = element_blank(),      
        axis.text.y = element_blank(),       
        legend.position = 'right')+  
  coord_flip()+ 
  geom_segment(aes(y=0, yend=0,x=0,xend=18.5))+
  geom_text(data = data[which(data$lda>0),],aes(x=s, y=-0.1, label=s),  
            hjust=1, size=4,color="black")+ 
  geom_text(data = data[which(data$lda<0),],aes(x=s, y=0.1, label=s),      
            hjust=0, size=4,color="black")+ 
  scale_x_discrete(expand = expansion(mult = c(0,0)))+
  ylim(-6, 6)+ 
  labs(x='Species', y='LDA')
load("data/G_5d.RData")
ggplot(data,aes(reorder(s, lda),lda,fill=group))+  
  geom_col()+  
  theme_bw()+  
  theme(panel.grid.major=element_blank(),        
        panel.grid.minor=element_blank(),       
        panel.border = element_blank(),   
        legend.title = element_blank(),   
        axis.text = element_text(color="black",size=10),   
        axis.line.x = element_line(color='black',size=0.05),   
        axis.ticks.y = element_blank(),      
        axis.text.y = element_blank(),       
        legend.position = 'right')+  
  coord_flip()+ 
  geom_segment(aes(y=0, yend=0,x=0,xend=18.5))+
  geom_text(data = data[which(data$lda>0),],aes(x=s, y=-0.1, label=s),  
            hjust=1, size=4,color="black")+ 
  geom_text(data = data[which(data$lda<0),],aes(x=s, y=0.1, label=s),      
            hjust=0, size=4,color="black")+ 
  scale_x_discrete(expand = expansion(mult = c(0,0)))+
  ylim(-6, 6)+ 
  labs(x='Species', y='LDA')
```

## H.R

```{r H, echo=TRUE}
# Functional dotplot (con vs 12h and 3d vs 5d)
rm(list = ls())
library(tidyverse)
load("data/H.RData")
ggplot(data, aes(time, description)) + 
  geom_point(aes(fill = report_score),
             shape = 21, color = "black",size = 6) + 
  facet_grid(group~., scales = "free", space='free', switch = "y") +
  # scale_size_continuous(breaks = seq(1, 6, 1), limits = c(1, 6),
  #                       range = c(1, 6)) +
  scale_fill_distiller(palette = "Greens", direction = 1) +
  #scale_fill_gradient(low = 'white', high = 'red') +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black", linewidth = 1),
        strip.background.y = element_rect(color="white"),
        strip.placement = "outside",
        strip.text.y = element_text(size = 13, color = "black", face = "bold"),
        axis.text.x = element_text(angle = 90, color = "black", size = 13, hjust = 1), 
        axis.text.y = element_text(color = "black", size = 13, vjust = 0.5),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 13),
        legend.text=element_text(size=13)) + 
  guides(fill = guide_colorbar(ticks = FALSE, 
                               barheight = 8, 
                               frame.colour = "black")) + 
  labs(x = "", y = "", 
       fill = "Pathway reporter score", 
       size = "Pathway reporter score") +
  ggpubr::rotate_x_text(hjust = 1)

# (rest of H.R code)
```





---

