---
title: "Figure2 R scripts combined"
output: html_document
---

This R Markdown combines the R scripts under `scripts/Figure2` into one document. Each script is included as a separate R code chunk (full original contents).

## A.R

```{r A, echo=TRUE}
########## 堆叠图
######### P1-control
library(tidyverse)
library(stringr)
library(ggplot2)
library(cowplot)

aa <- list.files("data/Differential gene analysis/")
df <- as.data.frame(NULL)
plot_data <- as.data.frame(NULL)
for (l in 1:length(aa)) {
  bb <- paste0("data/Differential gene analysis/",aa[l],"/")
  cc <- list.files(bb)
  for (i in 1:length(cc)) {
    dd <- paste0(bb,cc[i])
    jj <- str_split(cc[i],"_Control")[[1]][1]
    data <- read.csv(dd)
    data <- subset(data, abs(logFC) >= 1 & padj <= 0.05)
    df[i,1] <- nrow(data)
    df[i,2] <- jj
    df[i,3] <- aa[l]
  }
  plot_data <- rbind(plot_data,df)
}
colnames(plot_data) <- c("num","time","organ")
plot_data <- subset(plot_data,time != "Sham")
plot_data$time <- factor(plot_data$time,levels = c("SCI_0min","SCI_30min","SCI_1h","SCI_6h","SCI_12h",
                                                   "SCI_1d","SCI_3d","SCI_5d","SCI_7d","SCI_14d",
                                                   "SCI_1m","SCI_2m","SCI_3m"))
p1 <- ggplot(plot_data,aes(organ,num,fill=time))+
  #柱状堆积图
  geom_col(position = "fill")+
  #颜色
  coord_flip() +
  scale_fill_manual(values = c("#9f81b8","#e8c0ba","#f7b6d1","#855aa5","#f57f1f",
                               "#76c043","#d52928","#3388c9","#269e68","#1fbfd0",
                               "#fcba78","#aec7e8","#f69796"))+
  #主题
  labs(x = "", y = "Control Proportion", fill = 'Time') +
  theme_bw(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        plot.margin = margin(15,0,15,0),
        legend.position = "none")


############ P3 control+双Y轴
library(tidyverse)
library(stringr)
library(ggplot2)
aa <- list.files("data/Differential gene analysis/")
df <- as.data.frame(NULL)
plot_data <- as.data.frame(NULL)
for (l in 1:length(aa)) {
  bb <- paste0("data/Differential gene analysis/",aa[l],"/")
  cc <- list.files(bb)
  for (i in 1:length(cc)) {
    dd <- paste0(bb,cc[i])
    jj <- str_split(cc[i],"_Control")[[1]][1]
    data <- read.csv(dd)
    data <- subset(data, abs(logFC) >= 1 & padj <= 0.05)
    df[i,1] <- nrow(data)
    df[i,2] <- nrow(subset(data, logFC >= 1))
    df[i,3] <- nrow(subset(data, logFC <= -1))
    df[i,4] <- jj
    df[i,5] <- aa[l]
  }
  plot_data <- rbind(plot_data,df)
}
colnames(plot_data) <- c("All","Up","Down","time","organ")
plot_data <- subset(plot_data,time != "Sham")
plot_data <- plot_data[,c("All","Up","Down","organ")]
plot_data <- plot_data %>%
  group_by(organ) %>%
  summarise(across(everything(), sum))

data_1 <- plot_data[,c("Up","Down","organ")]


p3 <- ggplot()+ 
  geom_point(data = data_1, aes(x = organ, Up,fill = "UP"),color="#d39ac1",size=1)+
  geom_line(data = data_1,aes(x = organ, Up,fill = "UP",group=1),color="#d39ac1",cex=0.8)+ 
  geom_point(data = data_1,aes(x = organ, Down,fill = "Down"), color="#decc33", size=1)+
  geom_line(data = data_1,aes(x = organ, Down,group=1,fill = "Down"),color="#decc33",cex=0.8)+
  coord_flip()+
  labs(x = "", y = "Control Number") +
  theme_bw(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        axis.ticks.y  = element_blank(),
        axis.ticks.length.y = unit(0, "pt"),
        plot.margin = margin(15,0,15,0),
        legend.position = "none")


# Extract legends
legend_p1 <- get_legend(p1 + theme(legend.position = "right"))
legend_p3 <- get_legend(p3 + theme(legend.position = "right"))

combined_legend <- gridExtra::arrangeGrob(legend_p1,legend_p3, ncol = 1)

# Combine plots and legends
combined_plot <- plot_grid(p1, p3,  nrow = 1, align = "h", rel_widths = c(1, 0.75))
final_plot <- plot_grid(combined_plot, combined_legend, nrow = 1, rel_widths = c(1, 0.2))

# Display the final plot
print(final_plot)
```

## B.R

```{r B, echo=TRUE}
######## 柱状图
rm(list = ls())
library(ggplot2)
library(tidyverse)
library(gground)
library(ggprism)
data_1 <- read.csv("data/SCI_12h_up.csv",row.names = 1)
aa <- c("regulation of lipid storage",
        'regulation of lipase activity',
        "regulation of leukocyte cell-cell adhesion",
        "regulation of chemokine production",
        "lipid catabolic process",
        "hormone transport",
        "regulation of mast cell activation",
        "leukocyte proliferation",
        "lymphocyte proliferation",
        "monocyte chemotaxis")
data_1 <- subset(data_1,Description %in% aa)
data_1 <- data_1[,c(2,6,9)]
data_1 <- cbind(group = "fat_12h",data_1)
data_1$Description <- paste0(data_1$Description,"_fat")

data_2 <- read.csv("data/SCI_2m_up.csv",row.names = 1)
aa <- c("morphogenesis of a branching epithelium",
        'immune response-activating cell surface receptor signaling pathway',
        "alpha-beta T cell differentiation",
        "regulation of leukocyte cell-cell adhesion",
        "tissue remodeling",
        "NK T cell differentiation",
        "peptidyl-tyrosine phosphorylation",
        "regulation of glucose metabolic process",
        "regulation of hormone secretion",
        "regulation of glycolytic process")
data_2 <- subset(data_2,Description %in% aa)
data_2 <- data_2[,c(2,6,9)]
data_2 <- cbind(group = "marrow_2m",data_2)
data_2$Description <- paste0(data_2$Description,"_marrow")
data <- rbind(data_2,data_1)


enrich_df <- data %>%
  mutate(part = factor(group, levels = c("marrow_2m","fat_12h"))) %>%
  group_by(group) %>%
  arrange(p.adjust) %>%
  mutate(
    group_rank = row_number(),
    alpha_value = scales::rescale(-log10(p.adjust), to = c(0.3,0.8))
  ) %>%
  ungroup() %>%
  mutate(
    Description = factor(
      Description,
      levels = with(., Description[order(part, -group_rank)])
    )
  )

width <-0.5

xaxis_max <- max(-log10(enrich_df$p.adjust)) +1

rect.data <- enrich_df %>%
  group_by(part) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(
    ymax = cumsum(n),
    ymin = lag(ymax, default =0) +1, 
    xmin = -0.8, 
    xmax = -0.4
  )
color_mapping <- c(
  "marrow_2m"="#4DBBD5",
  "fat_12h"="#E64B35"
)
enrich_df %>%
  ggplot(aes(-log10(p.adjust), y = Description, fill = part)) +
  geom_round_col(
    aes(y = Description,alpha = alpha_value), width =0.8) +
  geom_text(
    aes(x =0.05, label = Description),
    hjust =0, size =5
  ) +
  geom_round_rect(
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax,
        fill = part),
    data = rect.data,
    alpha = 0.8,
    radius = unit(2,'mm'),
    inherit.aes =FALSE
  ) +
  geom_text(
    aes(x = (xmin + xmax) /2, y = (ymin + ymax) /2, label = part),
    data = rect.data,
    angle = 90,
    hjust = 0.5,
    vjust = 0.5,
    size = 5,
    inherit.aes =FALSE
  ) +
  annotate(
    "segment",
    x = 0, y = 0, 
    xend = xaxis_max, yend = 0,
    linewidth = 1.5
  ) +
  labs(y =NULL) +
  scale_fill_manual(values = color_mapping,guide = "none") +
  scale_alpha_identity()+
  scale_x_continuous(
    breaks = seq(0, xaxis_max,1),
    expand = expansion(c(0,0))
  ) +
  theme_prism() +
  theme(
    axis.text.y = element_blank(),
    axis.line = element_blank(),
    axis.ticks.y = element_blank(),
    legend.title = element_text()
  )
ggsave(file = "output/Fig.2/B/barplot.pdf",width = 9,height =8 )
```

## C.R

```{r C, echo=TRUE}
####### 炎症
rm(list = ls())
library(ggplot2) #绘图使用
library(clusterProfiler) #数据处理使用
library(GSVA) #GSVA使用
library(GSEABase) #数据处理使用
library(dplyr) #数据处理使用
library(data.table) #数据读取使用
library(pheatmap)
library(tidyverse)

load("data/GSVA_kegg_bp_geneset/240331_latest_GOBP.Rda")
load("data/GSVA_kegg_bp_geneset/240331_latest_keggpath1BP.Rda")

gcSample <- c(bppath,keggpath1)
# 处理名字

gcSample <- lapply(
  split(gcSample, names(gcSample)),          # 按名字分组
  function(x) do.call(c, x)        # 合并同组内的向量；如为 data.frame 可改用 rbind 等
)

gs = lapply(gcSample, unique) #每个列表里面的基因去重
# gsc <- GeneSetCollection(mapply(function(geneIds, gsva_resultId) {
#   GeneSet(geneIds, geneIdType=EntrezIdentifier(),
#           collectionType=gsva_resultCollection(gsva_resultId),
#           setName=gsva_resultId)
# }, gs, names(gs)))
# gsc  #list和GeneSetCollection格式都可以
## 2.2直接下载的基因集
# gene_set <- getGmt("./data/Homo/fatty acid metabolism.gmt")  #对应功能基因集

aa <- list.files("data/tpm_mean_filter/")
aa <- paste0("data/tpm_mean_filter/",aa)
aa <- aa[c(3,5,6,7,8,10,12,13)]
for (i in 1:length(aa)) {
  gsva_data <- read.csv(aa[i],row.names = 1)
  jj <- str_split(str_split(aa[i],"/")[[1]][3],".csv")[[1]][1]
  #### GSVA富集分析
  gsva_result <- gsva(as.matrix(gsva_data),  # 输入的表达数据需要`matrix`格式的
                      gs,  # Gene sets provided either as a list object or as a GeneSetCollection object
                      method = "gsva", # GSVA算法的选择。这里选择了"gsva"，也可以选择"ssgsea"-一般ssgsea用于免疫浸润
                      min.sz=1, # 基因集中允许的最小基因数。默认为1，表示允许基因集中只包含一个基因。
                      max.sz=Inf,# 基因集中允许的最大基因数。默认为Inf，表示没有最大限制，可以包含任意多个基因
                      kcdf="Gaussian",# 输入counts值使用"Poisson"。输入标准化之后的值(tpm/fpkm)，需要使用"Gaussian"
                      parallel.sz=1L)# 并行计算的规模。设置为1L，表示使用单线程计算
  ## GSVA结果，其中行名就是富集的通路，列名为样本名，值就是对应通路的GSVA得分。
  #### 下一步可以做何种分析
  ##  聚类：通过GSVA得到的样本富集得分，可以用于对样本进行聚类分析，可以对样本进行分型。
  ##  差异分析：GSVA结果还可以使用limma包进行差异分析，获得差异通路。
  ##  机器学习/深度学习模型的输入：GSVA结果可以用于构建分类器，对样本进行预测，例如将肿瘤样本与正常样本进行区分，或预测不同临床亚型。
  ##  与表型关联：将GSVA得分与临床特征或表型数据相关联，可以发现基因集富集与特定生物学表型之间的关联。
  gsva_result <- as.data.frame(gsva_result)
  gsva_result <- gsva_result[,-2]
  pp <- stringr::str_to_title(jj)
  name <- c("Fatty acid biosynthesis",
            "Glycolysis / Gluconeogenesis",
            "Starch and sucrose metabolism",
            "Fructose and mannose metabolism",
            "Fatty acid metabolism",
            "Tryptophan metabolism",
            "Mucin type O-glycan biosynthesis",
            "2-Oxocarboxylic acid metabolism",
            "Terpenoid backbone biosynthesis",
            "D-Amino acid metabolism",
            "Inositol phosphate metabolism",
            "Phosphonate and phosphinate metabolism",
            "Lysine degradation",
            "Histidine metabolism",
            "Riboflavin metabolism",
            "Pantothenate and CoA biosynthesis",
            "adaptive immune memory response",
            "helper T cell extravasation",
            "negative regulation of NK T cell activation",
            "mast cell apoptotic process",
            "regulation of neutrophil degranulation",
            "mast cell proliferation",
            "cytotoxic T cell differentiation",
            "regulation of neutrophil extravasation",
            "regulation of chronic inflammatory response",
            "NK T cell differentiation",
            "extrathymic T cell differentiation",
            "positive regulation of T cell migration")
  gsva_result <- gsva_result[name,]
  p <- pheatmap(gsva_result,
                color = colorRampPalette(c("#3672b6", "white", "#e92e22"))(100),
                border="black",#边框颜色
                main = pp,#指定图表的标题
                show_rownames = T,#是否展示行名
                show_colnames = T,#是否展示列名
                cexCol = 1,#指定列标签的缩放比例。
                scale = 'row',#指定是否应按行方向或列方向居中和缩放，或不居中和缩放。对应的值为row, column和none。
                cluster_col=F,#分别指定是否按列和行http://127.0.0.1:22479/graphics/cfdda67e-d6be-4a3a-b75f-8a004a9ebe8f.png聚类。
                cluster_row=F,
                cellwidth = unit(0.5, "cm"),
                cellheight = unit(0.5, "cm"),
                border_color = "black",
                angle_col = "45",#指定列标签的角度。
                legend = T,#指定是否显示图例。
                fontsize_row = 8,#分别指定行标签和列标签的字体大小。
                fontsize_col = 8,
                legend_breaks = c(-2, 0, 2))
   jj <- paste0("output/",jj,".pdf")
  ggsave(p, file=jj, width=7, height=15,limitsize = FALSE)
}
```

## D.R

```{r D, echo=TRUE}
rm(list = ls())
library(tidyverse)
############
cc <- c("Il6","Il10","Hk2","Pfkl")
bb <- c("spinal_tpm.csv","colon_tpm.csv","small_tpm.csv",
        "fat_tpm.csv","marrow_tpm.csv")
bb <- paste0("data/tpm_filter/",bb)

remove_last_part <- function(string) {
  sub("(.*?)(_[^_]*)$", "\\1", string)
}
for (pp in 1:length(cc)) {
  df <- data.frame(NULL)
  for (i in 1:length(bb)) {
    data <- read.csv(bb[i],row.names = 1)
    jj <- str_split(str_split(bb[i],"/")[[1]][4],"_")[[1]][1]
    data <- data[cc[pp],]
    data <- data[,-c(1:3,8:11)]
    rownames(data) <- jj
    colnames(data) <- sapply(colnames(data), remove_last_part)
    data <- cbind(organ = rownames(data),data)
    df <- rbind(df,data)
  }
  aa <- c("Control","SCI_0min","SCI_30min","SCI_1h","SCI_6h",
          "SCI_12h","SCI_1d","SCI_3d","SCI","SCI_7d","SCI_14d",
          "SCI_1m","SCI_2m","SCI_3m")
  df[,-1] <- log2(df[,-1] + 1)
  df <- df %>%
    pivot_longer(cols = -"organ", names_to = "group", values_to = "num")
  df$group <- sapply(df$group, remove_last_part)
  df$group <- factor(df$group,levels = aa)
  df$group <- as.numeric(df$group)
  
  
  # 数据准备：计算每组均值
  df_summary <- df %>%
    group_by(organ, group) %>%
    summarise(
      mean_num = mean(num),
      sd = sd(num)
    )
  
  # 创建折线图：以group为x轴，mean_num为y轴，按Group分组
  p <- ggplot(df_summary, aes(x = group, y = mean_num, group = organ, color = organ)) +
    
    # 添加折线、单点和趋势线
    # geom_line(linewidth = 1.2, algroupa = 0.8) +          # 固定线宽
    # geom_point(data = df_summary, aes(y = mean_num),      # 保留单点，使用原始num
    #            shape = 16, size = 2, algroupa = 0.6) +   # 固定点大小+
    # geom_errorbar(aes(ymin=mean_num-sd, 
    #                   ymax=mean_num+sd),
    #               size=1.05)+
    # 设置学术风格主题
    geom_smooth(aes(group = organ), method = "loess", 
                se = FALSE, linewidth = 1) + 
    theme_minimal(base_size = 14) +                     # 简洁主题，基础字体大小
    theme(
      panel.grid.major = element_line(color = "grey85", size = 0.3),  # 浅灰细网格线
      panel.grid.minor = element_blank(),                 # 移除次网格线
      axis.line = element_line(color = "black"),          # 黑色坐标轴
      axis.ticks = element_line(color = "black"),         # 黑色刻度线
      legend.position = "right",                          # 图例置右
      legend.box = "vertical",                            # 图例垂直排列
      legend.title = element_text(face = "bold"),         # 图例标题加粗
      plot.title = element_text(hjust = 0.5, face = "bold", size = 16),  # 标题居中加粗
      plot.subtitle = element_text(hjust = 0.5, size = 12)  # 副标题居中
    ) +
    
    # 设置颜色和标签
    scale_color_manual(values = c("spinal" = "#bce2b5", 
                                  "colon" = "#fcb461",
                                  "small"  = "#fee0bf",
                                  "fat"  =  "#dec2df",
                                  "marrow"  = "#d69f9f"),  # 自定义颜色
                       name = "Group") +                      # 仅保留Group图例
    labs(
      title = cc[pp],
      y = "log2(TPM + 1)"
    )+    
    theme_classic()+
    scale_x_continuous(breaks = seq(1,14), labels = c("Control","SCI_0min","SCI_30min","SCI_1h","SCI_6h",
                                                    "SCI_12h","SCI_1d","SCI_3d","SCI_5d","SCI_7d","SCI_14d",
                                                    "SCI_1m","SCI_2m","SCI_3m"))
  
  
  # 显示图形
  print(p)
  dd <- paste0("output/Fig.2/hexinjiyin/",cc[pp],".pdf")
  # 可选：保存为高质量图片
  ggsave(p,file = dd,width = 9.5, height = 6.5)
}
```

## F.R

```{r F, echo=TRUE}
rm(list = ls())
library(tidyverse)
############ Colon
data <- data.table::fread("data/2_Browse/Abundance_NR_RPKM_相对丰度/tax_s_RPKM_percent.xls",data.table = F)
data <- data %>%
  separate(col = `#Taxonomy`, into = c("d", "k", "p","c","o","f","g","s"), sep = ";", remove = FALSE)
data <- data[,-c(1:8)]
rownames(data) <- data$s
data <- data[,-1]
##### Co
df <- as.vector(NULL)
aa <- c("Con_","Sham_","SCI_0min_","SCI_30min_","SCI_1h_",
        "SCI_6h_","SCI_12h_","SCI_1d_","SCI_3d_","SCI_5d_",
        "SCI_7d_","SCI_14d_","SCI_1m_","SCI_2m_","SCI_3m_")
for (i in 1:length(aa)) {
  bb <- paste0(paste0(aa[i],c(1:6)),"_Co")
  df <- c(df,bb)
}
Co <- data[,df]
Co <- Co %>% 
  mutate(totle = rowSums(.)) %>%
  top_n(10, wt = totle)
Co <- data.frame(ID = rownames(Co),Num = Co$totle)
inflamation <- data.table::fread("data/cytoscape/Colon/inflamation.csv",data.table = F)
name <- c("negative regulation of lymphocyte proliferation",
          "basophil activation involved in immune response",
          "chronic inflammatory response to non-antigenic stimulus",
          "immunoglobulin V(D)J recombination",
          "neutrophil mediated cytotoxicity",
          "mast cell differentiation",
          "leukocyte migration involved in inflammatory response",
          "T cell receptor V(D)J recombination",
          'pro-B cell differentiation',
          "cytotoxic T cell pyroptotic process",
          "leukocyte chemotaxis involved in inflammatory response")
inflamation <- subset(inflamation,meta %in% name)
inflamation <- inflamation[,3:5]
colnames(inflamation) <- c("meta","pathway","cor")

metabolism <- data.table::fread("data/cytoscape/Colon/metabolism.csv",data.table = F)
name <- c("Arginine biosynthesis",
          'Cobalamin transport and metabolism',
          "Fatty acid metabolism",
          "Fructose and mannose metabolism",
          "Glycerophospholipid metabolism",
          "Pantothenate and CoA biosynthesis",
          "Phosphonate and phosphinate metabolism",
          "Riboflavin metabolism",
          "Starch and sucrose metabolism",
          "Valine, leucine and isoleucine biosynthesis")
metabolism <- subset(metabolism,meta %in% name)
metabolism <- metabolism[,3:5]
colnames(metabolism) <- c("meta","pathway","cor")

data <- rbind(inflamation,metabolism)
write.table(data,file ="output/Fig.2/F/cytoscape/Co_cytoscape_data.txt", sep = "\t", quote = F,row.names = FALSE)

ID <- c(unique(data$pathway))
Num <- c(1)
point <- data.frame(ID,Num)
point <- rbind(point,Co)
write.table(point,file ="output/Fig.2/F/cytoscape/Co_point_data.txt", sep = "\t", quote = F,row.names = FALSE)



############ Il
rm(list = ls())
library(tidyverse)
data <- data.table::fread("data/2_Browse/Abundance_NR_RPKM_相对丰度/tax_s_RPKM_percent.xls",data.table = F)
data <- data %>%
  separate(col = `#Taxonomy`, into = c("d", "k", "p","c","o","f","g","s"), sep = ";", remove = FALSE)
data <- data[,-c(1:8)]
rownames(data) <- data$s
data <- data[,-1]
##### Co
df <- as.vector(NULL)
aa <- c("Con_","Sham_","SCI_0min_","SCI_30min_","SCI_1h_",
        "SCI_6h_","SCI_12h_","SCI_1d_","SCI_3d_","SCI_5d_",
        "SCI_7d_","SCI_14d_","SCI_1m_","SCI_2m_","SCI_3m_")
for (i in 1:length(aa)) {
  bb <- paste0(paste0(aa[i],c(1:6)),"_Il")
  df <- c(df,bb)
}
Co <- data[,df]
Co <- Co %>% 
  mutate(totle = rowSums(.)) %>%
  top_n(10, wt = totle) 
Co <- data.frame(ID = rownames(Co),Num = Co$totle)
inflamation <- data.table::fread("data/cytoscape/Il/inflamation.csv",data.table = F)
name <- c("regulation of type 2 immune response",
          "stimulatory killer cell immunoglobulin-like receptor signaling pathway",
          "mast cell proliferation",
          "acute inflammatory response to non-antigenic stimulus",
          "positive regulation of mast cell cytokine production",
          "neutrophil degranulation",
          "regulation of humoral immune response",
          "regulation of T-helper 17 type immune response",
          "positive regulation of acute inflammatory response to non-antigenic stimulus",
          "regulation of B cell chemotaxis",
          "NLRP3 inflammasome complex assembly",
          "susceptibility to T cell mediated cytotoxicity",
          "helper T cell diapedesis")
inflamation <- subset(inflamation,meta %in% name)
inflamation <- inflamation[,3:5]
colnames(inflamation) <- c("meta","pathway","cor")
metabolism <- data.table::fread("data/cytoscape/Il/metabolism.csv",data.table = F)
name <- c("Fructose and mannose metabolism",
          'Phenylalanine, tyrosine and tryptophan biosynthesis',
          "Folate biosynthesis",
          "Fatty acid biosynthesis",
          "Vitamin B6 metabolism",
          "Folate biosynthesis",
          "Riboflavin metabolism",
          "Pantothenate and CoA biosynthesis",
          "Caffeine metabolism",
          "Various types of N-glycan biosynthesis")
metabolism <- subset(metabolism,meta %in% name)
metabolism <- metabolism[,3:5]
colnames(metabolism) <- c("meta","pathway","cor")
data <- rbind(inflamation,metabolism)
write.table(data,file ="output/Fig.2/F/cytoscape/Il_cytoscape_data.txt", sep = "\t", quote = F,row.names = FALSE)
ID <- c(unique(data$pathway))
Num <- c(1)
point <- data.frame(ID,Num)
point <- rbind(point,Co)
write.table(point,file ="output/Fig.2/F/cytoscape/Il_point_data.txt", sep = "\t", quote = F,row.names = FALSE)





```

---

Notes:
- The full original R scripts A.R, B.R, C.R, D.R and F.R are embedded above as R chunks. You can knit this file to an HTML report or extract individual chunks as needed.
